# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

target 'GoL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  # Pods for GoL

  target 'GoLTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
